/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package io.dmarkwat.twitter.finagle.app

import io.dmarkwat.twitter.finagle.utilities.StringUtils

object App {
   def main(args: Array[String]): Unit = {
        val tokens = StringUtils.split(MessageUtils.getMessage())
        val result = StringUtils.join(tokens)
        println(result)
    }
}
